# Generated by Django 4.1.5 on 2023-01-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Headline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headingName", models.CharField(max_length=200)),
                ("dateCreated", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
