# Generated by Django 4.1.5 on 2023-01-10 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zander_blogs_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("dateCreated", models.DateTimeField(auto_now_add=True)),
                (
                    "heading",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zander_blogs_app.headline",
                    ),
                ),
            ],
        ),
    ]
